version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "8080:80"
    restart: always

  server:
    build: ./server
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
